/*
 *	loc.js
 *	---------------------------------------------------------
 *
 *	---------------------------------------------------------
 *
 *	author: Chen MingYuan
 *	for iTASK 5.0
 *	Copyright (c) 2005 - 2006 iTASK Team
 *
 *	created : 2005-10-16
 * modified : 2006-9-21
 *
 */

var Loc = {

colon	: '：',
to		: '到',
none	: '無',
yes		: '是',
no		: '否',
confirm	: '確定',
inherit	: '繼承',
search	: '搜索',
query	: '查詢',
choose	: '選擇',
save	: '保存',
remove	: '刪除',
cancel	: '取消',
create	: '新建',
add		: '添加',
share	: '共用',
edit	: '編輯',
remind	: '提醒',
empty	: '清空',
plan	: '計畫',
report	: '審批',
execute	: '執行',
finish	: '完成',
pigeonhole : '歸檔',
person	: '人員',
dept	: '部門',
group	: '群組',
senior	: '高級',
grade	: '評分',
unassort : '未分類',
operfail : '操作失敗',
opertip	 : '操作提示',
saveclose : '保存並關閉',
nodata	: '暫無數據',
measure : '尺寸',
click_zoom	: '點擊放大',
search_end	: '搜索結束',
newfolder : '新資料夾',
cancel_remove : '取消刪除',
choose_onlyone : '只能選擇一條記錄',
choose_atleastone	: '請至少選擇一項',
internet_error	: '抱歉，該操作無法執行，造成的原因可能有：\n\n1、該資料已被刪除或轉移\n2、您沒有相關許可權\n3、網路連接出現了問題',
xml_unmatch		: 'XML格式不符合需要',
loading			: '請稍候',
data_loading	: '資料處理中，請稍候..',
online_player : '線上播放機',
tree_movefail1	: '無法移動：目的檔案夾和原始檔案夾相同',
tree_movefail2	: '無法移動：目的檔案夾是原始檔案夾的子資料夾',
tree_target	: '請選擇目的檔案夾',
affair1 : '重要並且緊急',
affair2 : '重要但是不急',
affair3 : '不重要但較急',
affair4 : '不重要也不急',

form : {
	notnull	: '{0}不能為空',
	onlyone : '{0}中只能選擇一條記錄',
	toolong : '{0}的字元長度超出限制，請減少字元',
	nomatch	: '{0}的格式不符合規範，或包含非法字元',
	number_range : '{0}中的數字應滿足以下條件：\n1、>= {1}\n2、<= {2}',
	time_error	: '{0}的時間格式錯誤',
	time_start_end : '{0}應滿足以下條件：\n1、起始時間 {1} 結束時間',
	max_attach : '附件數量不能超過{0}',
	add_file : '繼續添加附件',
	add_multext : '繼續添加',
	invalid_obj : '{0}物件無效，請重新輸入或選擇！',
	submit_error : '抱歉，由於存在無法訪問的表單資訊，該操作已中止'
},


weekname : ['星期日','星期一','星期二','星期三','星期四','星期五','星期六'],
date : {
	year	: '年',
	month	: '月',
	day		: '日',
	sky		: '天',
	hour	: '時',
	minute	: '分',
	second	: '秒',
	today	: '今天',
	weeknow	: '本周',
	monthnow: '本月',
	calendar_title	: ['日','一','二','三','四','五','六'],
	todayis : '今天是yyyy年m月d日 {0}',
	ym1 : 'yyyy 年 m 月',
	y1 : 'yyyy 年'
},

errors : {
	endtime_before_starttime : '結束時間不能早於開始時間',
	editor_invalid : '需轉換為編輯狀態後才能使用編輯功能或者提交表單！',
	can_not_open_word : '不能打開WORD,請確認:\n1 您的OFFICE是否安裝正確，而且現在沒有損壞\n2 您必須把當前網站設置為可信網站\n3 在Internet選項裡->Internet->自訂級別裡對沒有標為安全的ActiveX 是否為起用或提示 '
},

confirms : {
	remove : '確定要刪除嗎？',
	giveup_modify : '放棄目前所做的修改嗎？',
	cant_revert : '該操作不可恢復，確定嗎？',
	exec : '是否確定要執行當前操作？',
	empty : '是否確定要清空？'
},

week_tree_unexam : '未批示',
export_rtf : '匯出成RTF',
export_pdf : '匯出成PDF',
search_result : '搜索結果',
search_nomatch : '沒有找到匹配項',
search_condi : '搜索依據',
all_extend : '全部展開',
all_collapse : '全部折疊',
online_person : '線上人員',
system_msg : '該消息由系統自動產生',

invalid_part : '{0}中該數據無效：{1}',
start_with : '從{0}開始',
from_to : '從{0}到{1}',


//modules
topweb : {
	logout : '退出',
	desk : '快捷桌面',
	newmsg : '您有新消息',
	config : '配置',
	favor : '我的最愛',
	half : '半屏顯示我的最愛',
	min : '最小化我的最愛',
	max : '最大化我的最愛',
	welcome : '歡迎您，{0}！',
	no_module : '請您先在個人設置中啟用該模組',
	sess_null : '您當前的SESSION已過期，請把您當前的工作保存到其他地方，以免丟失'
},
cms : {
	newsort : '新建分類',
	newquest : '新建問卷',
	newexpect : '新建期數',
	newcatg : '新建子欄目',
	newmenu : '新建子功能表',
	surveystat : '調查統計'
},
daily : {
	status1 : '計畫',
	status2 : '開始',
	status3 : '終止',
	tp1 : '任務',
	tp2 : '商務',
	tp3 : '約會',
	tp4 : '會議',
	tp5 : '學習',
	tp6 : '拜訪',
	tp7 : '來訪',
	tp8 : '生日',
	tp9 : '雜事',
	tpA : '其他'
},

resource : {
	tree_cantmove1 : '資源不能移出到其他的資源庫',
	flow_executor : '{0}({1})的執行人'
},
task : {
	tree_cantmove1 : '只能在"待辦任務 - 按樹形"之內移動',
	create : '新建任務',
	createchild : '新建子任務',
	createroot : '新建根任務',
	edit : '編輯任務',
	view : '查看任務',
	del : '刪除任務',
	fbk : '發表回饋',
	move : '移動任務',
	hand : '移交任務',
	report : '上報任務',
	favor : '加入收藏',
	msgadd : '加入提醒',
	mail : '郵件發送',
	relate : '任務相關',
	secure : '安全屬性',
	share : '共用任務',
	gantt : '進度圖示',
	lnkmaintain : '連結維護',
	lnkview : '連結查看',
	lnkmsg : '消息',
	lnkfvr : '收藏',
	look : '任務監視',
	nolook : '取消監視',
	lookmaintain : '監視維護',
	lookview : '監視查看',
	exe : '執行任務',
	end : '結束任務',
	cancel : '取消任務',
	pigeonhole : '歸檔任務',
	reportok : '通過上報',
	reportfail : '回絕上報',
	_export : '匯出任務',
	single : '單項',
	multi : '多項',
	publish : '發起流程',
	workon : '辦理工作',
	pro_view : '流程圖示',
	link : '關聯任務',
	quit : '退出任務'
},
orgview : {
	tt : '組織機構圖',
	custom_prop : '自訂屬性'
},
email : {
 receive_failure:'郵件接收失敗',
 clear_folder_before_del:'請在刪除前清空資料夾'
},

font : {
	song : '宋體',
	hei : '黑體',
	kai : '楷體_GBK',
	fang : '仿宋_GBK',
	lv : '隸書',
	you : '幼圓'
},

editor : {
	bold : '粗體',
	italic : '斜體',
	underline : '底線',
	strikethrough : '中劃線',
	justifyleft : '左對齊',
	justifycenter : '居中對齊',
	justifyright : '右對齊',
	justifyfull : '兩端對齊',
	insertunorderedlist : '插入專案符號',
	insertorderedlist : '插入編號',
	outdent : '減少縮進量',
	indent : '增加縮進量',
	fontname : '字體',
	fontsize : '字型大小',
	forecolor : '字體前景色',
	backcolor : '字體背景色',
	draw : '自選形狀',
	cut : '剪切',
	copy : '複製',
	paste : '粘貼',
	pastetext : '純文字粘貼',
	pasteword : '從Word中粘貼',
	undo : '撤銷',
	redo : '恢復',
	find : '查找/替換',
	removeformat : '清除格式',
	createlink : '插入或修改連結',
	unlink : '取消連結',
	image : '插入圖片',
	flash : '插入Flash',
	media : '插入多媒體',
	table : '表格',
	shortcut : '快捷輸入',
	preview : '全屏編輯',
	html : '編輯源碼',
	imgmod : '圖片屬性',
	tableadd : '插入表格',
	tablemod : '表格屬性',
	tablecell : '儲存格屬性',
	tablecellsplit : '拆分儲存格',
	tablecellrow : '表格行屬性',
	tablerowins0 : '在上方插入一行',
	tablerowins1 : '在下方插入一行',
	tablerowmerge : '向下合併一行',
	tablerowsplit : '拆分行',
	tablerowdel : '刪除行',
	tablecolins0 : '在左側插入一列',
	tablecolins1 : '在右側插入一列',
	tablecolmerge : '向右側合併一列',
	tablecolsplit : '拆分列',
	tablecoldel : '刪除列',
	fillcolor : '填充顏色',
	strokecolor : '線條顏色',
	regulation : '規則形狀',
	unregulation : '不規則形狀',
	line : '線條',
	text : '文字方塊',
	label : '標注',
	rectangle : '矩形',
	RoundRect : '圓角矩形',
	ArcRect : '弧形矩形',
	Oval : '橢圓',
	Diamond : '菱形',
	Diamond : '菱形',
	Parallelogram : '平行四邊形',
	UpTriangle : '向上等腰三角形',
	DownTriangle : '向下等腰三角形',
	Directness : '直角三角形',
	UpTrapezoid : '向上梯形',
	DownTrapezoid : '向下梯形',
	Hexagon : '六邊形',
	Pentagon : '五邊形',
	Octagon : '八邊形',
	BigBracket : '雙大括弧',
	FBigBracket : '左大括弧',
	RBigBracket : '右大括弧',
	MidBracket : '雙中括弧',
	FMidBracket : '左中括弧',
	RMidBracket : '右中括弧',
	Heart : '心形',
	beenline : '直線',
	zline : '折線',
	strokeweight : '線條粗細',
	lineType : '虛線類型',
	zorder : '疊放次序',
	maxZindex : '置於頂層',
	minZindex : '置於底層',
	topZindex : '上移一層',
	lowerZindex : '下移一層',
	arrowType : '箭頭樣式',
	addtext : '添加文字',
	_3D : '立體',
	no_3D : '取消立體'
},
datepicker : {
	oper_tip : '按一下轉到今天日期\n按兩下選中今天日期'
},

ps : function (s) {
	for (var i = 1; i < arguments.length; i++) {
		s = s.replace('{'+(i-1)+'}', arguments[i]);
	}
	return s;
},
end  : '結束'
}
